version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/API"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/src/UI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/test/API"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/test/UI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
